### ISSUE TITLE
Remove dependency on JSON.NET

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues.DocFx#14]
We should get rid of the dependency to JSON.NET, so that we can target .NET Standard, which is not supported by Fody Costura. Could be replaced by `DataContractJsonSerializer` like in [Cake.Issues.EsLint](https://github.com/cake-contrib/Cake.Issues.EsLint/pull/7)

**Comment by rinukkusu** [comment]
Looking at the test files in the `Cake.Issues.DocFx.Tests` project - are the entries really in that format without the enclosing brackets like a list in JSON format usually has?

**Comment by pascalberger** [comment]
@rinukkusu Unfortunately yes. Their logfile is some kind of pseuod JSON, which actually makes it quite hard to parse.
